name: Docker Image CI

on:
  push:
    tags:        
      - 'release:v[0-9].[0-9]'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        TAG=$(date +%s)
        docker build . --file Dockerfile --tag f4zination/table-sense-ai:$TAG
        docker push f4zination/table-sense-ai:$TAG
