name: Docker Image CI

on:
  push:
    tags:        
      - 'release:v[0-9].[0-9]'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag f4zination/table-sense-ai:$(date +%s) && docker push f4zination/table-sense-ai:$(date +%s)
